name: printinput
description: Prints the inputs passed to this action
inputs:
  what-to-print:
    description: What is to be printed
    required: true
    default: "banana"
runs:
  using: "composite"
  steps:
    - id: printinput
      run: ./.github/actions/printinput/printinput.sh ${{ inputs.what-to-print }}
      shell: bash