on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2

    - id: sample-docker-output
      name: sample-docker-output
      uses: ./.github/actions/sample-docker-output

    - id: sample-docker-processing
      name: sample-docker-processing
      uses: ./.github/actions/sample-docker-processing
      env:
        them_files: '${{ steps.sample-docker-output.outputs.processed-files }}'