on: [push]
jobs:
  A-job-to-say-hello:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Hello world says hello!
      uses: ./.github/actions/printinput
      with:
        what-to-print: "something!"
